WAC-32 Fetch "data hub stats" to show in the front end [incomplete]
fjelltopp/ckanext-who-afro pull request #16
Opened 2024-05-23 11:43 UTC by A-Souhei

## Description
Proposed helper function to return:

- number of active datasets
- 
- datasets updated this week
- 
- number of active users
- 
- number of organisations
- 
- number of countries (still need to to agree how countries will be represented in the system)
- 
- number of programmes (still need to agree how programmes will be represented in the system)

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [ ] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.
- [ ] I have assigned at least one label to this PR: "patch", "minor", "major".

2024-05-23 13:03 UTC, jonathansberry reviewed
Ok great effort toavina.  You've really solved some non trivial stuff here - like how to get datasets modified in the last week.   I've left my feedback - hope it is helpful!

2024-05-23 13:50 UTC, A-Souhei commented on ckanext/who_afro/templates/home/snippets/insights.html
> +                                <span>{{ stats['active_users'] }}</span>
I've used active_users but can change to active_users.

2024-05-28 16:07 UTC, jonathansberry requested changes
Great job Toavina!  This is looking really good now.  Just spotted a typo.  Then the remaining thing is really small - we should seek to get the helper `get_site_statistics()` through the toolkit as well.  At first I wasn't sure how to because I couldn't see it in the docs (but it seemed crazy that it wasn't possible) I bit of digging with a debugger (`dir(toolkit)`) revealed that there is actually `toolkit.h` from which we can get all registered helpers. 

Let's get this PR out of draft mode.  Clean up the description a bit. Make the final little changes.  Re-request my review and we'll get it merged.

2024-05-29 09:49 UTC, jonathansberry approved these changes

2024-05-29 09:50 UTC, merged