WAC-116 Indicator datasets
fjelltopp/ckanext-who-afro pull request #42
Opened 2024-08-08 15:07 UTC by jonathansberry

## Description

Reforms the dataset read page to align with Lewi's design.  

Introduces an "Overview" endpoint.  The idea here is that we can load a pre-designed dashboard based on the dataset metadata.  

A helper determines whether a pre-designed dashboard exists (currently set to only return true if the dataset type is an indicator). 

When this is the case, the first tab loaded upon dataset read is the "overview" tab which gets the full package metadata.  I assume @ChasNelson1990 can take it from there in the metadata. 

N.B. This is definitely work that has been somewhat rushed! There are places where it is not pixel-perfect aligned with Lewis' design (I'm also not sure this design has been given the usual level of scrutiny due to the time pressure though) and I'm fully expecting there to be some gotchas in the coe. 

Some screenshots below...

The overview page

![image](https://github.com/user-attachments/assets/67ad6489-6efe-4369-a9b1-117711a4db80)

![image](https://github.com/user-attachments/assets/830c2253-a42b-43fb-8798-a2440b7b0719)

![image](https://github.com/user-attachments/assets/b45ae8d2-7f47-4eb3-99a4-0173eb722765)

## Dependency Changes (delete if not applicable)

List any dependencies that have been removed/added/changed in this pull request and explain why.
Has the pipfile.lock or yarn.lock been updated?
If dependency management for this project is centralised, e.g. `adx_deploy` for ADR, please link to the coordinated PR in the project repo.

## Testing (delete if not applicable)

Please describe the rationale behind any new tests that have been added for this change, e.g.

- I have included automated unit tests for all features except V, because W
- I have included automated integration tests for X that do Y
- I have not included automated UI tests because Z
- I have manually carried out the following tests that I have been unable to automate: A, B, C

## Documentation (delete if not applicable)

Please describe any new technical documentation that has been added to Confluence for this change.

## Environment Changes (delete if not applicable)

Have any environment variable changes been committed as part of this pull request?
Is there a matching PR in fjelltopp/fjelltop-infrastructure for these changes?
Have any README or Confluence install instructions been updated to reflect this change?

## Internationalisation and Localisation (delete if not applicable)

Do any UI changes require internationalisation (i18n) or localisation (l10n) changes.
If new translations are required, have you created new Jira tickets for each language and informed the appropriate project manager?

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [ ] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.
- [ ] I have assigned at least one label to this PR: "patch", "minor", "major".

2024-08-09 08:01 UTC, ChasNelson1990 commented
I can't seem to create new packages in the UI with this branch because of:
```sh
Traceback (most recent call last):
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 157, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckan/views/dataset.py", line 701, in get
    return base.render(
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckan/templates/package/new.html", line 9, in top-level template code
    {% block subtitle %}{{ h.humanize_entity_type('package', dataset_type, 'create title') or _('Create Dataset') }}{% endblock %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckan/templates/package/base_form_page.html", line 1, in top-level template code
    {% extends "package/edit_base.html" %}
  File "/usr/lib/ckan/ckanext-who-afro/ckanext/who_afro/templates/package/edit_base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckan/templates/package/edit_base.html", line 1, in top-level template code
    {% extends 'package/base.html' %}
  File "/usr/lib/ckan/ckanext-who-afro/ckanext/who_afro/templates/package/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckan/templates/package/base.html", line 4, in top-level template code
    {% set dataset_type = dataset_type or pkg.type or 'dataset' %}
  File "/usr/lib/ckan/ckanext-who-afro/ckanext/who_afro/templates/page.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckanext/activity/templates/page.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckan/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/ckan/ckanext-who-afro/ckanext/who_afro/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckanext/activity/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/src/ckanext-scheming/ckanext/scheming/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/src/ckanext-googleanalytics/ckanext/googleanalytics/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/src/ckanext-geoview/ckanext/geoview/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckan/templates/base.html", line 108, in top-level template code
    {%- block page %}{% endblock -%}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/ckan/templates/page.html", line 19, in block 'page'
    {%- block content %}
  File "/usr/lib/ckan/ckanext-who-afro/ckanext/who_afro/templates/page.html", line 4, in block 'content'
    {% block promoted_toolbar %}
  File "/usr/lib/ckan/ckanext-who-afro/ckanext/who_afro/templates/package/base.html", line 10, in block 'promoted_toolbar'
    {%- set package_type = h.scheming_get_dataset_schema(pkg.type).get('name', pkg.type) -%}
  File "/usr/lib/ckan/.minikubevenv/ckan-ALitmJXH/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'pkg_dict' is undefined
```

2024-08-09 08:09 UTC, ChasNelson1990 requested changes
Basically this template doesn't work for creating new datasets in the UI: /home/chas/work/who-afro/who-afro-ckan/ckanext-who-afro/ckanext/who_afro/templates/package/base.html

(I have turned the banner off temporarily on my local system to unblock me on the JS - once I've got a JS PR I will try and address this problem - if not, Monday!.

2024-08-12 21:46 UTC, jonathansberry commented
I have fixed the dataset creation bug and the js dashboard and merged into this branch. 

I think think we should look together at this tomorrow and merge in asap.

2024-08-13 10:52 UTC, ChasNelson1990 approved these changes

2024-08-13 10:53 UTC, merged